[package]
name = "hyper"
version = "0.1.0"
authors = ["Rousan Ali <rousanali786@gmail.com>"]
edition = "2021"

[dependencies]
hyper = { version = "0.14.26", features = ["full"] }
tokio = { version = "1.17.0", features = ["full"] }
